### ISSUE TITLE
Disable caching of Helix Pages sites

### ISSUE THREAD

**Issue by stefan-guggisberg** [adobe/helix-home#135]
## Overview
Helix Pages sites (`*.hlx.page`, `*.helix.page`) currently don't cache `Dispatch` type requests but do cache all other types (e.g. `.json`). This is confusing and makes debugging issues on the inner CDN very difficult, as experienced several times.

## Details
See https://github.com/adobe/helix-pages/issues/17, https://github.com/adobe/helix-dispatch/issues/49,

## Proposed Actions
Disable caching via `recv` VCL Snippet in the Helix Pages service configuration: https://docs.fastly.com/en/guides/temporarily-disabling-caching#disabling-caching-at-the-site-level

The VCL snippet only needs to be added once and is not affected by subsequent activations. 

This would provide a clean separation of concerns: The outer CDN caches, the inner CDN doesn't.

@davidnuescheler @trieloff @kptdobe @tripodsan WDYT?

**Comment by kptdobe** [comment]
I think the fact that we cache or not cache some requests is a bug, we should be consistent.

If I remember well, we had to do it in `Dispatch` because Fastly requests `Dispatch` as a browser would do it, i.e. it respects the headers it receives from the response and cache accordingly, thus I am not sure if the setting would solve that. Also what are the response headers set then ? 
I am fine if this solution is better than current impl. To be tested!

**Comment by trieloff** [comment]
I agree that we need a consistent way of disabling caching and that it's probably best done through a Fastly config rather than code within the actions. 

I don't think the approach suggested by @stefan-guggisberg will work as the VCL snippet would be injected here:

https://github.com/adobe/helix-publish/blob/5d0e57d74ee3d7255718d3ecb66da5f17b198229/layouts/fastly/helix.vcl#L1187

and that means none of the Helix request types will come to play. But we can try.

**Comment by stefan-guggisberg** [comment]
> I don't think the approach suggested by @stefan-guggisberg will work

Agreed. It doesn't work reliably because the location where the snipper is inserted into the generated vcl can't be really controlled.

As an alternative I've tried with a `hit` vcl snippet: `return (pass);`. That seems to do the trick.

**Comment by davidnuescheler** [comment]
after some discussions i think that the inner CDN should not cache any output, however it should cache content (as represented by the content proxy in the shape of `.md` and `.json`), assuming that we can purge those on change of the original document (docs and sheets) in one drive or gdrive.

**Comment by stefan-guggisberg** [comment]
I agree with David. Closing this issue/proposal (zero caching for inner CDN).
