### ISSUE TITLE
Create Markup Caching Service in Fastly

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-home#89]
For:

- [ ] word2md
- [ ] googledocs2md
- [ ] raw.githubusercontent.com

 Invalidated via bot (same as the index update) and cached forever (at least for word2md and googledocs2md and GH urls with a commit hash)

**Comment by trieloff** [comment]
We'll probably need some local equivalent in `helix-simulator`

**Comment by tripodsan** [comment]
the vector that addresses a markdown used for helix-pages is basically the  helix-pages url, eg:
`https://repo-owner.project-helix.page/blog.html`. but the md files keys are then addressed by:

- the fstab
- the original source (onedrive drive item, gdocs file, github file)

so, either the fstab resolution is done before requesting the md, by the pipeline. or it is moved behind the cache in a respective action.

1.  if the resource resolution is done by the pipeline, then the md file is requested with something like:
```
https://api.project-hellix.page/markdown/onedrive/{driveId}/{path}
https://api.project-hellix.page/markdown/gdocs/{folderId}/{path}
https://api.project-hellix.page/markdown/github/{giturl}
```

which would the invoke the respective `*2md` action or fetch from github.

2. if the fstab resolution is done later, then the resource could be requested using the entire url:
```
https://api.project-hellix.page/markdown/owner/repo/ref/path
```
which would invoke `helix-resolve-fstab` action, which reads from the repo and returns the resolved information (action + arguments). fastly would then restart and request from the desired source.

(1) has the advantage, that it is very transparent and the fstab evaluation can be done in the pipeline and probably be easy modified. but it includes an extra request. it also has the advantage that the fastly-cache does not need to be flushed when the fstab changes.

(2) has the advantage that it cache includes the resource resolution which would speed up the pipeline quite a lot. but it also it much more difficult to flush.

---

the cache invalidation needs to be triggered by a change listener to the sources. if the md cache also includes github, then this would imply that the user needs to install the helix-bot in the repository.
I think that `raw.githubusercontent.com` is quite fast and has no rate limit. so I don't think that we should cache those.

for (2) a bot listening on github is definitely needed.

---

I would start with (1) and only for word2md (because we already have created the listeners). then add gdocs support and eventually github.

**Comment by trieloff** [comment]
I haven't considered moving fstab resolution into a service (closer to `resolve-git-ref`) and always assumed that we'd pull this from `pre.js` into `helix-pipeline`. 

To better understand what's going on, I've drawn a chart of the status quo:

![Current Situation](https://user-images.githubusercontent.com/39613/72600566-2d475480-3914-11ea-9c02-ffc1ed43d918.png)

The red edges are the critical path to rendering a markdown, the red nodes are Runtime actions with potential rate limits. Like @tripodsan I don't see `raw.githubusercontent.com` as rate limited.

If we would pull the FSTab resolution into the pipeline, we'd be able to eliminate or at least parallelize one request to `raw.githubusercontent.com`, which results in an overall shorter critical path:

![FSTab in Pipeline](https://user-images.githubusercontent.com/39613/72600764-8c0cce00-3914-11ea-8187-a99e6ef09337.png)

The final retrieval would be either a plain HTTP request to `raw` or an action invocation (for word and google), hence the dotted border.

Doing the FSTab resolution already in the `helix-dispatch` function, right after calling `resolve-git-ref`, wouldn't shorten the critical path:

![FSTab in Dispatch](https://user-images.githubusercontent.com/39613/72601004-e3ab3980-3914-11ea-8321-705a8fa30405.png)

---

With that in mind, I'd follow @tripodsan's recommendation:

- [ ] pull the FSTab resolution into `helix-pipeline`
- [ ] build a Fastly cache for `helix-word2md`
- [ ] invalidate the above cache through the existing listeners

**Comment by trieloff** [comment]
However, we could also build a small experimental `helix-resolve-fstab` service that takes `owner`, `repo`, `ref`, `path`, fetches the `fstab.yaml` from `https://raw.githubusercontent.com/${owner}/${repo}/${ref}/fstab.yaml`, parses it using `helix-shared` finds the matching sub-path in a similar vein as [`helix-pages`](https://github.com/adobe/helix-pages/blob/master/src/html.pre.js) does and returns the resolved URL.

**Comment by tripodsan** [comment]
> However, we could also build a small experimental `helix-resolve-fstab` service ...

and how would that work with local development? the pipeline would have a special case to know that it runs locally and do the fstab resolution anyways....I would stick to _t1_ above.

**Comment by trieloff** [comment]
We have helix-content-proxy now
